php artisan make:migration sliders
php artisan make:migration categories
php artisan make:migration idukas
php artisan make:migration posts
php artisan make:migration post_categories
php artisan make:migration internships
php artisan make:migration internships_applies
php artisan make:migration documents
php artisan make:migration account_links
php artisan make:migration projects
php artisan make:migration project_applies
php artisan make:migration project_updates
php artisan make:migration project_categories
