php artisan make:model Post_Category
php artisan make:model Iduka
php artisan make:model Internship
php artisan make:model Internships_Apply
php artisan make:model Document
php artisan make:model Project
php artisan make:model Account_Link
php artisan make:model Project_Apply
php artisan make:model Project_Update
php artisan make:model Project_Category
php artisan make:model Post
php artisan make:model Category
